const students = [
  {
    Year: 2007,
    Name: "Reyes, Sofia",
    Course: "Bachelor of Science in Accountancy",
    "Shelf Location": "Shelf N, Row 4",
  },
  {
    Year: 2007,
    Name: "Santos, Miguel",
    Course: "Bachelor of Science in Business Administration Major in Human Resource Management",
    "Shelf Location": "Shelf N, Row 5",
  },
  {
    Year: 2008,
    Name: "Cruz, Ethan",
    Course: "Bachelor of Science in Business Administration Major in Marketing Management",
    "Shelf Location": "Shelf M, Row 4",
  },
  {
    Year: 2008,
    Name: "Gonzales, Isabella",
    Course: "Bachelor in Secondary Education Major in English",
    "Shelf Location": "Shelf M, Row 5",
  },
  {
    Year: 2009,
    Name: "Gonzales, Isabella",
    Course: "Bachelor in Secondary Education Major in Filipino",
    "Shelf Location": "Shelf L, Row 4",
  },
  {
    Year: 2009,
    Name: "Ramos, Gabriel",
    Course: "Bachelor of Science in Education Major in Mathematics",
    "Shelf Location": "Shelf L, Row 5",
  },
  {
    Year: 2010,
    Name: "Hernandez, Amelia",
    Course: "Bachelor of Science in Industrial Engineering",
    "Shelf Location": "Shelf K, Row 4",
  },
  {
    Year: 2010,
    Name: "Torres, Mateo",
    Course: "Bachelor of Science in Information Technology",
    "Shelf Location": "Shelf K, Row 5",
  },
  {
    Year: 2011,
    Name: "Castro, Lucas",
    Course: "Bachelor of Science in Psychology",
    "Shelf Location": "Shelf J, Row 4",
  },
  {
    Year: 2011,
    Name: "Dela Cruz, Mia",
    Course: "Bachelor in Technology And Livelihood Education Major in Home Economics",
    "Shelf Location": "Shelf J, Row 5",
  },
  {
    Year: 2012,
    Name: "Lim, Sophia",
    Course: "Bachelor of Science in Management Accounting",
    "Shelf Location": "Shelf I, Row 4",
  },
  {
    Year: 2012,
    Name: "Villanueva, Rafael",
    Course: "Bachelor of Science in Accountancy",
    "Shelf Location": "Shelf I, Row 5",
  },
  {
    Year: 2013,
    Name: "Pascual, Diego",
    Course: "Bachelor of Science in Business Administration Major in Human Resource Management",
    "Shelf Location": "Shelf H, Row 4",
  },
  {
    Year: 2013,
    Name: "Sison, Camila",
    Course: "Bachelor of Science in Business Administration Major in Marketing Management",
    "Shelf Location": "Shelf H, Row 5",
  },
  {
    Year: 2014,
    Name: "Aquino, Elijah",
    Course: "Bachelor in Secondary Education Major in English",
    "Shelf Location": "Shelf G, Row 4",
  },
  {
    Year: 2014,
    Name: "Garcia, Ava",
    Course: "Bachelor in Secondary Education Major in Filipino",
    "Shelf Location": "Shelf G, Row 5",
  },
  {
    Year: 2015,
    Name: "Ramirez, Noah",
    Course: "Bachelor of Science in Education Major in Mathematics",
    "Shelf Location": "Shelf F, Row 4",
  },
  {
    Year: 2015,
    Name: "Tan, Olivia",
    Course: "Bachelor of Science in Industrial Engineering",
    "Shelf Location": "Shelf F, Row 5",
  },
  {
    Year: 2016,
    Name: "Mercado, Emily",
    Course: "Bachelor of Science in Psychology",
    "Shelf Location": "Shelf E, Row 5",
  },
  {
    Year: 2016,
    Name: "Salazar, Adrian",
    Course: "Bachelor in Technology And Livelihood Education Major in Home Economics",
    "Shelf Location": "Shelf E, Row 10",
  },
  {
    Year: 2017,
    Name: "Del Rosario, Benjamin",
    Course: "Bachelor of Science in Management Accounting",
    "Shelf Location": "Shelf D, Row 4",
  },
  {
    Year: 2017,
    Name: "Yap, Lily",
    Course: "Bachelor of Science in Accountancy",
    "Shelf Location": "Shelf D, Row 5",
  },
  {
    Year: 2018,
    Name: "Fernandez, Dominic",
    Course: "Bachelor of Science in Information Technology",
    "Shelf Location": "Shelf C, Row 4",
  },
  {
    Year: 2018,
    Name: "Santos, Alexander",
    Course: "Bachelor of Science in Business Administration Major in Human Resource Management",
    "Shelf Location": "Shelf C, Row 5",
  },
  {
    Year: 2019,
    Name: "Reyes, Victoria",
    Course: "Bachelor of Science in Business Administration Major in Marketing Management",
    "Shelf Location": "Shelf B, Row 4",
  },
  {
    Year: 2019,
    Name: "Santos, Alexander",
    Course: "Bachelor of Science in Psychology",
    "Shelf Location": "Shelf B, Row 5",
  },
];
